services:

  nginx:
    container_name: nginx
    build: ../infra-nginx-dockerized
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - spring_net
    depends_on:
      - helloworld
      - modules
      - accounts
      - documentation

  database:
    container_name: database
    env_file:
      - .env
    image: postgres:17
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - spring_net

  accounts_redis:
    container_name: accounts_redis
    env_file:
      - .env
    image: redis:latest
    command: [
      "redis-server",
      "--port", "6379",
      "--requirepass",
      "${ACCOUNTS_REDIS_PASSWORD}",
      "--notify-keyspace-events", "Ex"
    ]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - spring_net

  documentation:
    container_name: documentation
    env_file:
      - .env
    build: ../documentation
    ports:
      - "${DOCUMENTATION_PORT}:${DOCUMENTATION_PORT}"
    networks:
      - spring_net

  helloworld:
    container_name: helloworld
    env_file:
      - .env
    build: ../helloworld
    ports:
      - "${HELLOWORLD_PORT}:${HELLOWORLD_PORT}"
    networks:
      - spring_net

  accounts:
    container_name: accounts
    env_file:
      - .env
    build: ../accounts
    ports:
      - "${ACCOUNTS_PORT}:${ACCOUNTS_PORT}"
    networks:
      - spring_net
    depends_on:
      - database
      - accounts_redis

  modules:
    build: ../modules
    env_file:
      - .env
    expose:
      - "${MODULES_PORT}"
    networks:
      - spring_net
    depends_on:
      - accounts
    deploy:
      replicas: 3

volumes:
  postgres_data:
  redis_data:

networks:
  spring_net:
    driver: bridge