spring.application.name=modules
server.port=${MODULES_PORT}

# Database
spring.datasource.url=jdbc:${DATABASE_TYPE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DATABASE_DDL}
spring.jpa.properties.hibernate.default_schema=modules
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.create-schemas=true
spring.flyway.schemas=modules
spring.flyway.default-schema=modules
spring.flyway.table=flyway_modules_history
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=true